[package]
name = "oricon_release"
version = "0.1.0"
authors = ["github5884 <github5884@example.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
