# compiler
CXX = g++
# compile options
CXXFLAGS = -std=c++11
# execution file
TARGET = npl
# target source files
SRCS = npl.cpp
# object files
OBJS = npl.o

################################

# compile
$(TARGET): $(OBJS)
	$(CXX) ${CXXFLAGS} ${OBJS} -o ${TARGET}
